Fallback to Component when PureComponent missing
Fix build error on React 0.13 and 0.14:
TypeError: Super expression must either be null or a function